import { ICharacter } from "./types";

export const arr: ICharacter[] = [
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "123",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "123",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "123",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "123",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "123",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "123",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "123",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "123",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "123",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "123",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "start NEW",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "Adanel",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "Adanel",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "Adanel",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "Adanel",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "Adanel",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "Adanel",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "Adanel",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "Adanel",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "Adanel",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "Adanel",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "Adanel",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "Adanel",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "Adanel",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "Adanel",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "Adanel",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "Adanel",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "Adanel",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "Adanel",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
    {
        _id: "5cd99d4bde30eff6ebccfbbe",
        birth: null,
        death: null,
        gender: "Female",
        hair: null,
        height: null,
        name: "Adanel",
        race: "Human",
        realm: null,
        spouse: "Belemir",
        wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
    },
];

export const DEFAULT_CHARACTER: ICharacter = {
    _id: "5cd99d4bde30eff6ebccfbbe",
    birth: "",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "start NEW",
    race: "Human",
    realm: "",
    spouse: "Belemir",
    wikiUrl: "http://lotr.wikia.com//wiki/Adanel",
};
